name: socket-security-workflow
run-name: Socket Security Github Action
on: [push, issue_comment]
jobs:
  socket-security:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Socket CLI
        run: pip install socketsecurity --upgrade
      - name: Check if Default Branch
        if: steps.branch-names.outputs.is_default == 'true'
        run: echo "DEFAULT_BRANCH=1" >> $GITHUB_ENV
      - name: Save Pull Request Number
        id: get_pr_data
        run: |
          RESULT=$(curl -X GET --header "Authorization: Bearer $GH_API_TOKEN" -H "User-Agent: TestPythonScript/1.0" https://api.github.com/repos/${{ github.repository }}/commits/${{ github.ref_name }}/pulls)
          if [ ! -z $RESULT ] && [ $RESULT != "" ]; then
            PR_NUMBER_RESULT=$(echo $RESULT | jq '.[].number')
          fi
          if [ -z $PR_NUMBER_RESULT ] || [ $PR_NUMBER_RESULT == "" ]; then
            "PR_NUMBER=${{ github.event.issue.number }}"  >> $GITHUB_ENV
          else
            "PR_NUMBER=$PR_NUMBER_RESULLT"  >> $GITHUB_ENV
          fi
      - name: Run scan
        env:
          SOCKET_SECURITY_API_KEY: ${{ secrets.SOCKET_SECURITY_API_KEY }}
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          echo socketcli --scm github --repo ${{ github.event.repository.name }} --branch "${{ github.ref_name }}" $(if [ ! -z $DEFAULT_BRANCH ]; then echo "--default_branch"; fi) --pr_number $(if [ -z $PR_NUMBER ]; then echo 0; else echo $PR_NUMBER;fi) --committer "$GITHUB_ACTOR" --commit_message "$COMMIT_MESSAGE" --target_path $GITHUB_WORKSPACE
          socketcli --scm github --repo ${{ github.event.repository.name }} --branch "${{ github.ref_name }}" $(if [ ! -z $DEFAULT_BRANCH ]; then echo "--default_branch"; fi) --pr_number $(if [ -z $PR_NUMBER ]; then echo 0; else echo $PR_NUMBER;fi) --committer "$GITHUB_ACTOR" --commit_message "$COMMIT_MESSAGE" --target_path $GITHUB_WORKSPACE
